# Config file for automatic testing at travis-ci.org

language: python

sudo: false

python:
  - 3.5
  - 3.4
  - 3.3
  - 2.7
  - 2.6

env:
  matrix:
  - DJANGO='django16-sekizai'
  - DJANGO='django16-nosekizai'
  - DJANGO='django17-sekizai'
  - DJANGO='django17-nosekizai'
  - DJANGO='django18-sekizai'
  - DJANGO='django18-nosekizai'
  - DJANGO='django19-sekizai'
  - DJANGO='django19-nosekizai'
  - TOXENV='pep8'
  - TOXENV='isort'
  - TOXENV='docs'


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox>=1.8 coveralls
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then export PYVER=py26; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then export PYVER=py27; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then export PYVER=py33; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then export PYVER=py34; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PYVER=py35; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOXENV=$PYVER-$DJANGO; fi"

# command to run tests, e.g. python setup.py test
script: COMMAND='coverage run' tox -e"$TOXENV"

before_install:
  - pip install codecov
after_success:
  - codecov
  - coveralls

matrix:
  exclude:
  - python: 2.6
    env: DJANGO='django17-sekizai'
  - python: 2.6
    env: DJANGO='django17-nosekizai'
  - python: 2.6
    env: DJANGO='django18-sekizai'
  - python: 2.6
    env: DJANGO='django18-nosekizai'
  - python: 2.6
    env: DJANGO='django19-sekizai'
  - python: 2.6
    env: DJANGO='django19-nosekizai'

  - python: 3.3
    env: DJANGO='django19-sekizai'
  - python: 3.3
    env: DJANGO='django19-nosekizai'

  - python: 3.5
    env: DJANGO='django16-sekizai'
  - python: 3.5
    env: DJANGO='django16-nosekizai'
  - python: 3.5
    env: DJANGO='django17-sekizai'
  - python: 3.5
    env: DJANGO='django17-nosekizai'

  - python: 2.6
    env: TOXENV='pep8'
  - python: 2.6
    env: TOXENV='isort'
  - python: 2.6
    env: TOXENV='docs'
  - python: 2.7
    env: TOXENV='pep8'
  - python: 2.7
    env: TOXENV='isort'
  - python: 2.7
    env: TOXENV='docs'
  - python: 3.3
    env: TOXENV='pep8'
  - python: 3.3
    env: TOXENV='isort'
  - python: 3.3
    env: TOXENV='docs'
  - python: 3.4
    env: TOXENV='pep8'
  - python: 3.4
    env: TOXENV='isort'
  - python: 3.4
    env: TOXENV='docs'

cache:
   directories:
     - $HOME/.pip-accel
     - $HOME/.cache/pip
