# Config file for automatic testing at travis-ci.org
dist: xenial
language: python

sudo: false

python:
  - 3.7
  - 3.6
  - 3.5
  - 2.7

env:
  matrix:
  - DJANGO='django111-sekizai'
  - DJANGO='django111-nosekizai'
  - DJANGO='django20-sekizai'
  - DJANGO='django20-nosekizai'
  - DJANGO='django21-sekizai'
  - DJANGO='django22-nosekizai'
  - TOXENV='pep8'
  - TOXENV='isort'
  - TOXENV='docs'


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U setuptools 'tox>=1.8' coveralls
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then export PYVER=py27; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PYVER=py35; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then export PYVER=py36; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then export PYVER=py37; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOXENV=$PYVER-$DJANGO; fi"

# command to run tests, e.g. python setup.py test
script: COMMAND='coverage run' tox -e"$TOXENV"

before_install:
  - pip install codecov
after_success:
  - codecov
  - coveralls

matrix:
  exclude:
  - python: 2.7
    env: TOXENV='pep8'
  - python: 2.7
    env: TOXENV='isort'
  - python: 2.7
    env: TOXENV='docs'
  - python: 2.7
    env: DJANGO='django20-sekizai'
  - python: 2.7
    env: DJANGO='django20-nosekizai'
  - python: 2.7
    env: DJANGO='django21-sekizai'
  - python: 2.7
    env: DJANGO='django21-nosekizai'
  - python: 2.7
    env: DJANGO='django22-sekizai'
  - python: 2.7
    env: DJANGO='django22-nosekizai'
  - python: 3.5
    env: TOXENV='pep8'
  - python: 3.5
    env: TOXENV='isort'
  - python: 3.5
    env: TOXENV='docs'
  - python: 3.5
    env: DJANGO='django111-sekizai'
  - python: 3.5
    env: DJANGO='django111-nosekizai'
  - python: 3.6
    env: TOXENV='pep8'
  - python: 3.6
    env: TOXENV='isort'
  - python: 3.6
    env: TOXENV='docs'
  - python: 3.6
    env: DJANGO='django111-sekizai'
  - python: 3.6
    env: DJANGO='django111-nosekizai'

cache:
   directories:
     - $HOME/.pip-accel
     - $HOME/.cache/pip
