dist: xenial
language: python

python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5
  - 2.7

env:
  matrix:
  - TOXENV='pep8'
  - TOXENV='isort'
  - TOXENV='docs'
  - DJANGO='django30-sekizai'
  - DJANGO='django30-nosekizai'
  - DJANGO='django22-sekizai'
  - DJANGO='django22-nosekizai'
  - DJANGO='django111-sekizai'
  - DJANGO='django111-nosekizai'


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U setuptools 'tox>=1.8' 'coveralls>=1.10.0'
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then export PYVER=py27; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PYVER=py35; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then export PYVER=py36; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.7' ]]; then export PYVER=py37; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then export PYVER=py38; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOXENV=$PYVER-$DJANGO; fi"

# command to run tests, e.g. python setup.py test
script: COMMAND='coverage run' tox -e"$TOXENV"

before_install:
  - pip install codecov
after_success:
  - codecov
  - coveralls

matrix:
  exclude:
  - python: 2.7
    env: TOXENV='pep8'
  - python: 2.7
    env: TOXENV='isort'
  - python: 2.7
    env: TOXENV='docs'
  - python: 2.7
    env: DJANGO='django22-sekizai'
  - python: 2.7
    env: DJANGO='django22-nosekizai'
  - python: 2.7
    env: DJANGO='django30-sekizai'
  - python: 2.7
    env: DJANGO='django30-nosekizai'
  - python: 3.5
    env: TOXENV='pep8'
  - python: 3.5
    env: TOXENV='isort'
  - python: 3.5
    env: TOXENV='docs'
  - python: 3.5
    env: DJANGO='django111-sekizai'
  - python: 3.5
    env: DJANGO='django111-nosekizai'
  - python: 3.5
    env: DJANGO='django30-sekizai'
  - python: 3.5
    env: DJANGO='django30-nosekizai'
  - python: 3.6
    env: TOXENV='pep8'
  - python: 3.6
    env: TOXENV='isort'
  - python: 3.6
    env: TOXENV='docs'
  - python: 3.6
    env: DJANGO='django111-sekizai'
  - python: 3.6
    env: DJANGO='django111-nosekizai'
  - python: 3.7
    env: TOXENV='pep8'
  - python: 3.7
    env: TOXENV='isort'
  - python: 3.7
    env: TOXENV='docs'
  - python: 3.7
    env: DJANGO='django111-sekizai'
  - python: 3.7
    env: DJANGO='django111-nosekizai'

cache: pip
