language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
install:
- pip install $DJANGO -r requirements_test.txt
env:
  - DJANGO="django>=1.4,<1.5"
  - DJANGO="django>=1.5,<1.6"
  - DJANGO="django>=1.6,<1.7"
script: coverage run runtests.py
after_success:
  coveralls
matrix:
  exclude:
    - python: 3.3
      env: DJANGO="django>=1.4,<1.5"
    - python: 3.4
      env: DJANGO="django>=1.4,<1.5"